twuni/docker-registry.helm

templates/service.yaml
Istio requires the service port to be named like `<protocol>[-<suffix>]`.
If possible, it would be good to rename it here to match this requirement.
=> Rename port to match Istio naming conventions

README.md, templates/deployment.yaml, templates/secret.yaml, values.yaml
This pull request adds support for configuring the registry as a proxy or pull-through cache, as documented [here](https://docs.docker.com/registry/recipes/mirror/). 
My use case for this configuration is to avoid [pull rate limits](https://docs.docker.com/docker-hub/download-rate-limit/) in kubernetes clusters where one may be deploying multiple applications at once such as after a cluster is initially created or when testing different configurations of an application, requiring multiple deployments.
=> Add support for registry proxy/mirror

README.md, templates/deployment.yaml, values.yaml
When using GitOps tools like Flux, we don't want the contents of values.yaml to be added to Git.
As such, it is desirable to load them from secrets created a priori.
This PR adds support for this, on the proxy config, through a `authExternalSecret` key that refs a specific secret in order to fulfill this usecase.
Let me know if this makes sense :)
=> Add support for having external proxy secrets

README.md, templates/deployment.yaml, values.yaml
Following the rationale on https://github.com/twuni/docker-registry.helm/pull/20, this PR adds support for externalizing s3 secrets.
Let me know if the changes make sense :)
=> Add support for having external s3 secrets

templates/secret.yaml
Setting up docker-registry proxy with no password & username created the secret without `proxyUsername` and `proxyPassword` fields, causing pod to fail if `proxy.enabled = true` with error 
```
error: "couldn't find key proxyUsername in Secret <namespace>/docker-registry-secret"
```
=> Add keys proxyUsername and proxyPassword with empty string to docker-registry-secret if values are not set

README.md, templates/deployment.yaml, values.yaml
Add support for S3 bucket to prefix all data
https://docs.docker.com/registry/storage-drivers/s3/
> This is a prefix that is applied to all S3 keys to allow you to segment data in your bucket if necessary.
=> Add support for S3 bucket data prefix

README.md, templates/configmap.yaml, templates/deployment.yaml, templates/ingress.yaml, templates/poddisruptionbudget.yaml, templates/pvc.yaml, templates/secret.yaml, templates/service.yaml
The charts didn't specify `metadata.namespace` anywhere so have added support for this. Have used the `{{ .Release.Namespace }}` variable which defaults to `default` if not set. This makes it a non-intrusive change for anyone not wanting to use it, but a useful change for those who do
Fixed #41
Have tested against my own cluster with these commands:
```shell
helm upgrade \
--atomic \
--cleanup-on-fail \
--install \
--wait \
registry .
```
This deploys `registry` to `default` namespace
```shell
helm upgrade \
--atomic \
--cleanup-on-fail \
--create-namespace \
--install \
--namespace registry \
--wait \
registry .
```
This deploys `registry` to `registry` namespace
=> Support deployment to a namespace

README.md, templates/deployment.yaml, templates/prometheusrules.yaml, templates/service.yaml, templates/servicemonitor.yaml, values.yaml
Added support to enable metrics of docker-registry and enabled integration with Prometheus Operator (https://github.com/prometheus-operator/prometheus-operator)
This enables metrics and native seamless integration of docker-registry setup with Prometheus Operator. This functionality enables both passing of metrics and alert configuration to Prometheus. This functionality is by default disable and user can enable it.
Specification if metrics are enabled:
- Metrics are be exposed on Pod and Service. 
- Pod port for metrics is set via `configData` while port for Service is set via values ( `.Values.metrics.port` )
- ServiceMonitor and PrometheusRule are deployed which are part of Prometheus Operator `monitoring.coreos.com/v1`
Credits for exposing metrics: …
=> Enable metrics via Prometheus Operator

templates/deployment.yaml, templates/service.yaml, templates/servicemonitor.yaml
Quick PR that renames the metrics port from `metrics` to `http-metrics` to make scraping work automatically with Istio protocol selection: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
We can also avoid renaming the port by means of using `appProtocol` on the Service Port spec, but figured if this was viable it works across a wider set of K8S versions.
=> 🌐 make protocol selection work with istio

templates/deployment.yaml
Too bad it's lacking a check, in addition to the config, that the secret file has not changed too in the deployment :)
=> fix(templates): Add checksum on secret.yaml file

README.md, templates/hpa.yaml, templates/hpaV1.yaml, values.yaml
Added Horizontal Pod Autoscaler to enable autoscaling of pods  
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
This enables configuration of autoscaling of pods containing docker registry. This functionality is disabled by default. 
Example of configuration:
```
autoscaling:
enabled: true
minReplicas: 2
maxReplicas: 5
targetCPUUtilizationPercentage: 50
```
=> Added support for pod autoscaling using Horizontal Pod Autoscaler

README.md, templates/deployment.yaml, values.yaml
This commit will give the user the ability to specify initContainers directly in the values file, which will then become part of the deployment.
=> Add initContainer support

README.md
https://github.com/twuni/docker-registry.helm/blob/f1583238750b54247c32b3d7cc1e6b72c0dbdc8c/templates/secret.yaml#L17
According to `secret.yaml` `haSharedSecret` should be inside `secrets` object
=> Fix reference in README

.github/workflows/pr_diff.yaml, templates/deployment.yaml
ref https://github.com/twuni/docker-registry.helm/pull/62#issuecomment-1210366076
example https://github.com/ddelange/docker-registry.helm/pull/5#issuecomment-1210654878
=> :construction_worker: Add sticky helm diff PR comment

templates/serviceaccount.yaml
When `serviceAccount.create` is `true`, this chart creates
a service account. Currently, that service account will be
created without an explicit namespace. This can be problematic
because the Deployment resource does have an explicit namespace
set. Because the ServiceAccount and Deployment (ultimately, the
Pod) must coexist in the same namespace, we need to follow the
same logic when setting the namespace for both.
Intended to fix https://github.com/twuni/docker-registry.helm/issues/60.
See https://github.com/twuni/docker-registry.helm/blob/main/templates/deployment.yaml#L5 and https://github.com/twuni/docker-registry.helm/blob/main/templates/secret.yaml#L5 for reference on how the namespace is being set in these other resources.
=> 🐞 Add missing namespace to ServiceAccount

README.md
The default tag has been 2.8.1 since the last release at the very least: https://github.com/twuni/docker-registry.helm/blob/v2.2.2/values.yaml#L22
=> Update README.md to use correct default version

README.md, templates/deployment.yaml, values.yaml
Closes #86
This adds the ability for users to specify annotations on the deployment.
=> Adding Deployment Annotations

artifacthub-repo.yml
Summary
-------
Artifact Hub supports a simple cross-reference mechanism for verifying a Helm chart's publisher. This changeset implements that, resulting in a "verified publisher" checkmark on this chart's listing on Artifact Hub.
Resources
---------
This chart is located on Artifact Hub at https://artifacthub.io/packages/helm/twuni/docker-registry.
More information about publisher verification at https://artifacthub.io/docs/topics/repositories/#verified-publisher
An **artifacthub-repo.yml** template is available at https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml
Note
----
I only included myself in the list of `owners`. Maintainers, please feel free to add yourselves here and elsewhere as you see fit.
=> 🔑 add publisher verification for artifact hub

.github/workflows/helm_release.yaml, .gitignore
The chart-releaser-action requires that helm charts be placed into chart/<chart_name> to work. I've tried configuring it appropriately for this repo, but couldn't get it to work.
Instead, I'm using that action to install just the chart-releaser binary. Then, I'm using the `cr` binary to package, release, and update the index in the gh-pages branch.
Any commit on the main branch will cause a new release as long as the chart version has changed.
=> chore: add helm release action

values.yaml
The `regionEndpoint` value does not work at all without one, so provide a nice hint that it is required in the vendor-provided materials.
Fixes Issue: #97
=> docs: Document that `s3.regionEndpoint` requires a transport scheme

templates/service.yaml, values.yaml
Labels can currently be specified for the ingress, servicemonitor, prometheusRules, and the registry pods themselves.
This expands that to the registry service, so that we can exclude it from velero snapshots and restores. (why? because we create this with a static IP address, and velero does not restore static IP addresses)
I would also be happy to expand this pattern to all of the other resources in the repository - the configmap, cronjob, deployment, hpa, pdb, pvc, secret and serviceaccount objects.
=> add the ability to specify labels for the registry service

README.md
Removed the $ sign to allow users to take advantage of the handy copy snippet functionality offered by the GitHub UI
=> [TINY] Fix copy command in README

templates/cronjob.yaml, values.yaml
This change will provide `podLabels` and `podAnnotations` options specific to the `garbageCollect` cronjob job pod with defaults to the root `podLabels` and `podAnnotations`. There are a few minor fixes for yaml rendering for the cronjob as well where spaces were left in the cronjob yaml. There are `podLabels` and `podAnnotations` options added in the `values.yaml` file and some minor spacing fixes in that file as well.
I used the [merge function](https://helm.sh/docs/chart_template_guide/function_list/#merge-mustmerge) in Helm along with [default](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function) and an empty [`dict`](https://helm.sh/docs/chart_template_guide/function_list/#dict) (dictionary). The logic and functions should prefer the …
=> Update garbageCollect cronjob

Chart.yaml
The most substantive change between 2.2.3 and 2.3.0 is setting `containerSecurityContext: true` by default. 
The pod was previously configured, via PodSecurityContext, to run as non-root user 1000. The additional container security context sets the container to also run as group 1000, drop all capabilities, and set a few other security settings. It looks to be using the [restricted pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted). The change's associated PR is [here](https://github.com/twuni/docker-registry.helm/pull/129).
Locally, using Orbstack, I am able to pull and push from the registry using this minimal config:
```yaml
ingress:
enabled: true
hosts:
- registry.k8s.orb.local
persistence:
enabled: true
```
Full change set is …
=> 🏁 v2.3.0 Release

README.md, templates/_helpers.tpl, values.yaml
Add ability to set the forcepathstyle value from the helm chart. This is needed to support certain s3 compatible applications.
Closes https://github.com/twuni/docker-registry.helm/issues/163
=> Add the ability to force path style for s3 storage

README.md, templates/_helpers.tpl, templates/cronjob.yaml, templates/deployment.yaml, values.yaml
=> [Fixes #135] Updated chart to accept configPath to fix distribution's 3.0.0 breaking change
